/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CommissionSummaryListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheCommissionSummaryListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Company Code");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Billing Date");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Sales Organization");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Cod.class.comm.");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Agent Code");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("SD Document");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Payer");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Max date");
            Then.onTheCommissionSummaryListGenerated.onFilterBar().iCheckFilterField("Date record alloc.");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheCommissionSummaryListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheCommissionSummaryListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheCommissionSummaryListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheCommissionSummaryListGenerated.onTable().iCheckColumns(undefined, {"Bukrs":{"header":"Societa"},"Fkdat":{"header":"Data fattura"},"Vkorg":{"header":"Org. commerciale"},"Zclpr":{"header":"Class. provv."},"Zcdaz":{"header":"Agente"},"Namea":{"header":"Ragione sociale"},"Vbeln":{"header":"Doc. commerciale"},"Kunrg":{"header":"Pagatore"},"Zimco":{"header":"Importo provv."},"Zimmg":{"header":"Importo maturato"},"Waerk":{"header":"Valuta"},"Zstre":{"header":"Stato record"},"Zidfs":{"header":"N. fac-simile"},"Zamcf":{"header":"Comp. fac-simile"},"Ztpcd":{"header":"Tipo blocco"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheCommissionSummaryListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheCommissionSummaryListGenerated.onTable().iCheckRows();

            When.onTheCommissionSummaryListGenerated.onTable().iPressRow(0);
            Then.onTheCommissionSummaryObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});